### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/font_awesome#1]
The README.md file for this project is not _quite_ properly formatted. 

The only real problem is the first heading.  If properly formatted, this heading (usually the project name) will be removed by backdropcms.org. Take a look at the modules page to see the problem: https://backdropcms.org/modules?keys=font

Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) that you can copy.

**Comment by thekenshow** [comment]
Just downloaded this module via the Backdrop site and it contains the README.md file for the parallax module instead of font_awesome:

> # PARALLAX BACKGROUND
> 
> This a simple module that allows you to set a vertical parallax effect...

**Comment by biolithic** [comment]
thanks for the issue -- what do these pages show you for a readme?

https://backdropcms.org/project/font_awesome

https://github.com/backdrop-contrib/font_awesome/blob/1.x-1.x/readme.md

I see a standard readme and will have to check out the download process later

**Comment by thekenshow** [comment]
I also see the correct README text in both of those locations.

**Comment by biolithic** [comment]
Ok, I will try to figure out later today, thanks for checking!

**Comment by Gormartsen** [comment]
@biolithic If you open this url:
https://github.com/backdrop-contrib/font_awesome/blob/1.x-1.1/readme.md (it's tag link from releases) you will see wrong readme

You need to do a new release now to replace readme inside release download zip file

**Comment by jenlampton** [comment]
It also looks like the module name is not the correct heading level in the README.

**Comment by jenlampton** [comment]
Closing as a dupe of https://github.com/backdrop-contrib/font_awesome/pull/5
