### ISSUE TITLE
Expose Font Awesome icons to core icon API

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/font_awesome#27]
This PR does the same for the Bootstrap Icons module and should be pretty straightforward to adapt for Font Awesome:
 - https://github.com/backdrop-contrib/bootstrap_icons/pull/4

**Comment by yorkshire-pudding** [comment]
Thanks @laryn - happy to accept a PR or I will try and get to this sometime soon.

**Comment by laryn** [comment]
@yorkshire-pudding Sure, I'll try to prepare a PR for your review.

**Comment by laryn** [comment]
@yorkshire-pudding Ready for review. This is locally with Icon Browser:

https://github.com/backdrop-contrib/font_awesome/assets/871421/1fbc3da4-fbd9-45b6-af60-7c5f686506e8

**Comment by yorkshire-pudding** [comment]
Thanks @laryn 

I've tested this and it looks great.  

I don't think it is related to this PR, but I'm getting warnings on the icon browser page when I click an icon:

>Warning: Undefined global variable $theme_key in _icon_from_theme() (line 137 of /app/docroot/core/includes/icon.inc).
>Warning: Undefined array key "" in _icon_from_theme() (line 158 of /app/docroot/core/includes/icon.inc).

Seems to also happen for clicking on core icons so I've opened a ticket in the icon browser repo - https://github.com/backdrop-contrib/icon_browser/issues/12

I'll probably wait until the 1.28.0 release to merge and release this

Many thanks
