### ISSUE TITLE
Request for maintainership

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/font_awesome#4]
Hi @biolithic,

I'm interested in using and updating this module. Was wondering if I could take over maintainership of it? The readme says you're seeking one (maintainer, that is)...

**Comment by ghost** [comment]
PR shows the changes I'd make.

**Comment by herbdool** [comment]
@bwpanda @jenlampton It looks like this module is abandoned and we have a potential new maintainer

**Comment by ghost** [comment]
Yep, still happy to take this over...

**Comment by jenlampton** [comment]
Since it's been more than 2 weeks since this issue was created with no response from the current maintainer, I am approving this request to take over maintainership. Thanks @BWPanda for offering to take over!
