### ISSUE TITLE
Accessibility and Font Awesome

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/font_awesome#6]
I'm not sure how/if this relates to the implementation used in this module, but wanted to mark it down for future review:

 - [Accessibility the Awesome Way: Making Icons More Accessible to Screen Readers](https://blog.kalamuna.com/news/accessibility-awesome-way-making-icons-more-accessible-screen-readers)

**Comment by ghost** [comment]
I skimmed the article and it seems to be saying that you shouldn't use `<i>` tags for icons. I don't believe we do that here (I think we use `<span>`), so will close this.
