### ISSUE TITLE
Allow field formatter to work with list_text as well

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/font_awesome#9]
In my use case I want to preset a bunch of icons for a field, and not leave it up to the author to know what classes mean.

This is easily done with the list_text field type. I've got it working so I can provide a pr soon.

~By the way, it wasn't clear at first where this formatter would be available and how one should use it. I had to look in the code.~ (Oops, I missed that part of the readme).

**Comment by herbdool** [comment]
@BWPanda I've got a PR.

**Comment by ghost** [comment]
Thanks @herbdool! I made a small change to fix the line length in the README, but otherwise merged your PR as-is.
